### ISSUE TITLE
多个账号

### ISSUE THREAD

**Issue by xiamo008** [PUREGIH/juliangip_dailycheckin#2]
你好大佬，请教下比如2个账号该如何写变量呢

**Comment by PUREGIH** [comment]
参考

```json
{
  "juliang_account": [
    "user1@1passwd@wxpusherUID",
    "user2@1passwd@wxpusherUID",
    "user3@1passwd"
  ],
  "juliang_api_config": [
    "trade_no@API_KEY",
    "trade_no_2@API_KEY",
    "trade_no_3@API_KEY"
  ]
}
```

**Comment by xiamo008** [comment]
> 参考
> 
> ```json
> {
>   "juliang_account": [
>     "user1@1passwd@wxpusherUID",
>     "user2@1passwd@wxpusherUID",
>     "user3@1passwd"
>   ],
>   "juliang_api_config": [
>     "trade_no@API_KEY",
>     "trade_no_2@API_KEY",
>     "trade_no_3@API_KEY"
>   ]
> }
> ```

谢谢大佬，祝老板生8个儿子
