### ISSUE TITLE
多账号就出现错误

### ISSUE THREAD

**Issue by xiamo008** [PUREGIH/juliangip_dailycheckin#3]
![1720507706355](https://github.com/PUREGIH/juliangip_dailycheckin/assets/90441350/73046554-cecb-4ceb-bd0d-d51fc3abcdd3)
辛苦大哥麻烦瞅瞅，我设置了2个变量，假设第一个变量已经签到过，脚本就会直接断了，不会继续运行，这是日志，有空麻烦瞅瞅呢~谢谢

**Comment by PUREGIH** [comment]
> ![1720507706355](https://github.com/PUREGIH/juliangip_dailycheckin/assets/90441350/73046554-cecb-4ceb-bd0d-d51fc3abcdd3)
> 
> 辛苦大哥麻烦瞅瞅，我设置了2个变量，假设第一个变量已经签到过，脚本就会直接断了，不会继续运行，这是日志，有空麻烦瞅瞅呢~谢谢

白天的时候我看看

**Comment by PUREGIH** [comment]
> ![1720507706355](https://private-user-images.githubusercontent.com/90441350/346843945-73046554-cecb-4ceb-bd0d-d51fc3abcdd3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1ODI3NjgsIm5iZiI6MTcyMDU4MjQ2OCwicGF0aCI6Ii85MDQ0MTM1MC8zNDY4NDM5NDUtNzMwNDY1NTQtY2VjYi00Y2ViLWJkMGQtZDUxZmMzYWJjZGQzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDAzMzQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNjQzNWI2M2NiYzNhODI2YmM3OGI5YjBmOGYwOGZjMGU3Y2MyOTc3N2QzZGU3OTQ2MmYyODYyYmM4OTY3ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tqPHwTLxE63bY-VPjhIZ8SQyo-DJrx9ufSVRMCdlXso) 辛苦大哥麻烦瞅瞅，我设置了2个变量，假设第一个变量已经签到过，脚本就会直接断了，不会继续运行，这是日志，有空麻烦瞅瞅呢~谢谢

参考配置文件[config.json](https://github.com/PUREGIH/juliangip_dailycheckin/blob/master/config.json) ，不需要的配置项置空

**Comment by xiamo008** [comment]
> > ![1720507706355](https://private-user-images.githubusercontent.com/90441350/346843945-73046554-cecb-4ceb-bd0d-d51fc3abcdd3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA1ODI3NjgsIm5iZiI6MTcyMDU4MjQ2OCwicGF0aCI6Ii85MDQ0MTM1MC8zNDY4NDM5NDUtNzMwNDY1NTQtY2VjYi00Y2ViLWJkMGQtZDUxZmMzYWJjZGQzLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDAzMzQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyNjQzNWI2M2NiYzNhODI2YmM3OGI5YjBmOGYwOGZjMGU3Y2MyOTc3N2QzZGU3OTQ2MmYyODYyYmM4OTY3ZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tqPHwTLxE63bY-VPjhIZ8SQyo-DJrx9ufSVRMCdlXso) 辛苦大哥麻烦瞅瞅，我设置了2个变量，假设第一个变量已经签到过，脚本就会直接断了，不会继续运行，这是日志，有空麻烦瞅瞅呢~谢谢
> 
> 参考配置文件[config.json](https://github.com/PUREGIH/juliangip_dailycheckin/blob/master/config.json) ，不需要的配置项置空

好的，可以了。谢谢大舅哥
