### ISSUE TITLE
无法加载json

### ISSUE THREAD

**Issue by xiamo008** [PUREGIH/juliangip_dailycheckin#5]
![image](https://github.com/user-attachments/assets/acc78f77-b524-4bea-859f-213cc1d1dec4)
![image](https://github.com/user-attachments/assets/1bc1bcaf-208a-4b79-ac0f-d39a49d46aad)
大佬 今天0点签到就不行了，提示这个，请教下这是什么问题啊

**Comment by PUREGIH** [comment]
> ![image](https://private-user-images.githubusercontent.com/90441350/348590078-acc78f77-b524-4bea-859f-213cc1d1dec4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwODMxNzUsIm5iZiI6MTcyMTA4Mjg3NSwicGF0aCI6Ii85MDQ0MTM1MC8zNDg1OTAwNzgtYWNjNzhmNzctYjUyNC00YmVhLTg1OWYtMjEzY2MxZDFkZWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDIyMzQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwYzVmMGY1ODQxZTg4NjdhNWZkMGMxNjE4ZDI4NThkYWE0ODQ4NzlhZmM2ODlhZTM2ZmFkYjhlYmUwYTMyMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s0wWZDXPzEC2TUVMxhn5ceJlbeafcjQt--ZWFMIxq1Q) ![image](https://private-user-images.githubusercontent.com/90441350/348590141-1bc1bcaf-208a-4b79-ac0f-d39a49d46aad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwODMxNzUsIm5iZiI6MTcyMTA4Mjg3NSwicGF0aCI6Ii85MDQ0MTM1MC8zNDg1OTAxNDEtMWJjMWJjYWYtMjA4YS00Yjc5LWFjMGYtZDM5YTQ5ZDQ2YWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDIyMzQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiN2E3YzliOTEzMGU5OTRkM2NmNzhjNjcwZDViZTQwMDdjNGIyMWRjMzQ0NzY3ZDg1ZmM5YzQ0OTIzMjAzNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y9v7fRmTbULUG5AGBylNEnETUzk79PmLN_blOjawNiM) 大佬 今天0点签到就不行了，提示这个，请教下这是什么问题啊

**json**不能有注释，不要直接复制MD文档里的配置，打开`config.json`配置文件手动编辑。不要复制。

**Comment by xiamo008** [comment]
> > ![图像](https://private-user-images.githubusercontent.com/90441350/348590078-acc78f77-b524-4bea-859f-213cc1d1dec4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwODMxNzUsIm5iZiI6MTcyMTA4Mjg3NSwicGF0aCI6Ii85MDQ0MTM1MC8zNDg1OTAwNzgtYWNjNzhmNzctYjUyNC00YmVhLTg1OWYtMjEzY2MxZDFkZWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDIyMzQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwYzVmMGY1ODQxZTg4NjdhNWZkMGMxNjE4ZDI4NThkYWE0ODQ4NzlhZmM2ODlhZTM2ZmFkYjhlYmUwYTMyMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s0wWZDXPzEC2TUVMxhn5ceJlbeafcjQt--ZWFMIxq1Q) ![图像](https://private-user-images.githubusercontent.com/90441350/348590141-1bc1bcaf-208a-4b79-ac0f-d39a49d46aad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwODMxNzUsIm5iZiI6MTcyMTA4Mjg3NSwicGF0aCI6Ii85MDQ0MTM1MC8zNDg1OTAxNDEtMWJjMWJjYWYtMjA4YS00Yjc5LWFjMGYtZDM5YTQ5ZDQ2YWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDIyMzQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiN2E3YzliOTEzMGU5OTRkM2NmNzhjNjcwZDViZTQwMDdjNGIyMWRjMzQ0NzY3ZDg1ZmM5YzQ0OTIzMjAzNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y9v7fRmTbULUG5AGBylNEnETUzk79PmLN_blOjawNiM)大佬今天0点签到就不行了，提示这个，请教下这是什么问题啊
> 
> **json**不能有注释，不要复制MD文档里的配置，打开`config.json`配置文件手动编辑。不要复制。

应该不是注释的问题，我之前是用的跟新之前没有注释哪一版，也不行，然后我下载下来 改的。

**Comment by xiamo008** [comment]
> > > ![图像](https://private-user-images.githubusercontent.com/90441350/348590078-acc78f77-b524-4bea-859f-213cc1d1dec4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwODMxNzUsIm5iZiI6MTcyMTA4Mjg3NSwicGF0aCI6Ii85MDQ0MTM1MC8zNDg1OTAwNzgtYWNjNzhmNzctYjUyNC00YmVhLTg1OWYtMjEzY2MxZDFkZWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDIyMzQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwYzVmMGY1ODQxZTg4NjdhNWZkMGMxNjE4ZDI4NThkYWE0ODQ4NzlhZmM2ODlhZTM2ZmFkYjhlYmUwYTMyMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s0wWZDXPzEC2TUVMxhn5ceJlbeafcjQt--ZWFMIxq1Q) ![图像](https://private-user-images.githubusercontent.com/90441350/348590141-1bc1bcaf-208a-4b79-ac0f-d39a49d46aad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwODMxNzUsIm5iZiI6MTcyMTA4Mjg3NSwicGF0aCI6Ii85MDQ0MTM1MC8zNDg1OTAxNDEtMWJjMWJjYWYtMjA4YS00Yjc5LWFjMGYtZDM5YTQ5ZDQ2YWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDIyMzQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiN2E3YzliOTEzMGU5OTRkM2NmNzhjNjcwZDViZTQwMDdjNGIyMWRjMzQ0NzY3ZDg1ZmM5YzQ0OTIzMjAzNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y9v7fRmTbULUG5AGBylNEnETUzk79PmLN_blOjawNiM)大佬今天0点签到就不行了，提示这个，请教下这是什么问题啊
> > 
> > 
> > **json**不能有注释，不要复制MD文档里的配置，打开`config.json`配置文件手动编辑。不要复制。
> 
> 应该不是注释问题，我之前用的跟新之前没有注释哪一版，也不行，然后我下载改的。

![image](https://github.com/user-attachments/assets/56a623bd-b793-4606-926d-39eb589d4a23)
这是我最新的格式

**Comment by xiamo008** [comment]
> > > ![图像](https://private-user-images.githubusercontent.com/90441350/348590078-acc78f77-b524-4bea-859f-213cc1d1dec4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwODMxNzUsIm5iZiI6MTcyMTA4Mjg3NSwicGF0aCI6Ii85MDQ0MTM1MC8zNDg1OTAwNzgtYWNjNzhmNzctYjUyNC00YmVhLTg1OWYtMjEzY2MxZDFkZWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDIyMzQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwYzVmMGY1ODQxZTg4NjdhNWZkMGMxNjE4ZDI4NThkYWE0ODQ4NzlhZmM2ODlhZTM2ZmFkYjhlYmUwYTMyMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s0wWZDXPzEC2TUVMxhn5ceJlbeafcjQt--ZWFMIxq1Q) ![图像](https://private-user-images.githubusercontent.com/90441350/348590141-1bc1bcaf-208a-4b79-ac0f-d39a49d46aad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwODMxNzUsIm5iZiI6MTcyMTA4Mjg3NSwicGF0aCI6Ii85MDQ0MTM1MC8zNDg1OTAxNDEtMWJjMWJjYWYtMjA4YS00Yjc5LWFjMGYtZDM5YTQ5ZDQ2YWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDIyMzQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiN2E3YzliOTEzMGU5OTRkM2NmNzhjNjcwZDViZTQwMDdjNGIyMWRjMzQ0NzY3ZDg1ZmM5YzQ0OTIzMjAzNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y9v7fRmTbULUG5AGBylNEnETUzk79PmLN_blOjawNiM)大佬今天0点签到就不行了，提示这个，请教下这是什么问题啊
> > 
> > 
> > **json**不能有注释，不要复制MD文档里的配置，打开`config.json`配置文件手动编辑。不要复制。
> 
> 应该不是注释问题，我之前用的跟新之前没有注释哪一版，也不行，然后我下载改的。

![image](https://github.com/user-attachments/assets/f3af8591-f967-4785-944a-3f3e56f6577c)
这是我现在的格式

**Comment by PUREGIH** [comment]
> > > > ![图像](https://private-user-images.githubusercontent.com/90441350/348590078-acc78f77-b524-4bea-859f-213cc1d1dec4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwODMxNzUsIm5iZiI6MTcyMTA4Mjg3NSwicGF0aCI6Ii85MDQ0MTM1MC8zNDg1OTAwNzgtYWNjNzhmNzctYjUyNC00YmVhLTg1OWYtMjEzY2MxZDFkZWM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDIyMzQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwYzVmMGY1ODQxZTg4NjdhNWZkMGMxNjE4ZDI4NThkYWE0ODQ4NzlhZmM2ODlhZTM2ZmFkYjhlYmUwYTMyMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s0wWZDXPzEC2TUVMxhn5ceJlbeafcjQt--ZWFMIxq1Q) ![图像](https://private-user-images.githubusercontent.com/90441350/348590141-1bc1bcaf-208a-4b79-ac0f-d39a49d46aad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwODMxNzUsIm5iZiI6MTcyMTA4Mjg3NSwicGF0aCI6Ii85MDQ0MTM1MC8zNDg1OTAxNDEtMWJjMWJjYWYtMjA4YS00Yjc5LWFjMGYtZDM5YTQ5ZDQ2YWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDIyMzQzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiN2E3YzliOTEzMGU5OTRkM2NmNzhjNjcwZDViZTQwMDdjNGIyMWRjMzQ0NzY3ZDg1ZmM5YzQ0OTIzMjAzNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y9v7fRmTbULUG5AGBylNEnETUzk79PmLN_blOjawNiM)大佬今天0点签到就不行了，提示这个，请教下这是什么问题啊
> 
> > > 
> 
> > > 
> 
> > > **json**不能有注释，不要复制MD文档里的配置，打开`config.json`配置文件手动编辑。不要复制。
> 
> > 
> 
> > 应该不是注释问题，我之前用的跟新之前没有注释哪一版，也不行，然后我下载改的。
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/f3af8591-f967-4785-944a-3f3e56f6577c)
> 
> 这是我现在的格式
> 
> 

[json校验](https://www.json.cn/)，去校验下看看格式合法么
