### ISSUE TITLE
滑动验证无法自动输入

### ISSUE THREAD

**Issue by johnzon520** [PUREGIH/juliangip_dailycheckin#6]
滑动验证无法自动输入，麻烦大佬帮忙看下哪里错误，谢谢
![1723422291710](https://github.com/user-attachments/assets/a0395a33-3b89-4143-8ed1-f5f840440b83)

**Comment by PUREGIH** [comment]
> 滑动验证无法自动输入，麻烦大佬帮忙看下哪里错误，谢谢
> 
> ![1723422291710](https://github.com/user-attachments/assets/a0395a33-3b89-4143-8ed1-f5f840440b83)
> 
> 

图鉴API账密配置了么？
有配置把执行点击签到动作后的延迟增大一点看看
